import mongoose from "mongoose";
import dotenv from "dotenv";
import Incident from "../models/incident.js";
import connectDB from "../config/database.js";

dotenv.config();
connectDB();

const seedData = async () => {
  try{
    await Incident.deleteMany();

    await Incident.insertMany([
      {
        title : "Autonomus car failed to detect person.",
        description : "An autonomus vehicle's vision model failed to detect a person crossing the road in low light conditions.",
        severity : "High",
      },
      {
        title : "Fake news generated by language model",
        description : "A large language model was used to generate realistic fake news at moderate scale.",
        severity : "Medium",
      },
      {
        title : "Content recommendation mismatch",
        description : "A streaming platform's AI recommended irrelevent videos to users, decreasing engagement temporarily.",
        severity : "Low",
      }
    ]);

    console.log("Sample incidents seeded");
    process.exit();

  } catch(error){
    console.error(error);
    process.exit(1);
  }
}

seedData();
